[Server]
Mode = "release"
IP = "0.0.0.0"
Port = "5000"
#LogPath = "./logs"
GRPCPort = 50052
CronType = "m"  # m 分钟级别 | s 秒级别

[Raft]
bootstrap = true    # 如果是第一台设置为true，否则为：false
httpAddress = "127.0.0.1:2869"
tcpAddress = "127.0.0.1:2889"   # 不能设置成: 0.0.0.0:2869, 必须是ip:port.
dataDir = "./raft_data"
joinAddress = ""    # 如果是第一台设置为空，否则设置第一台的httpAddress

[MySQL]
DBName = "jobor"
User = "xx"
Password = "xx"
Host = "xx"
Port = 3306
Parameters = "charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"


[Gorm]
Debug = false
DBType = "mysql"
TablePrefix = ""
MaxLifetime = 100
MaxOpenConn = 200
MaxIdleConn = 200

[Redis]
Host = "xxx:6379" # "xxxx:6379,xxxx:6379"
Password = ""
DB = 1

[JWT]
TokenType = "Bearer"     # Bearer
TokenKey = "jS2SnJdxxmTKRNQYh"
RefreshKey = "jreJdXxT0kenYh"
Age = 360000

[LDAP]
addr = "ad.example.org:389"
baseDn = "dc=example,dc=org"
bindDn = "cn=admin,dc=example,dc=org"
bindPass = "password"
authFilter = "(cn=%s)"   # "(&(sAMAccountName=%s))"
attributes = ["cn", "mail","displayName", "dn"] # ["sAMAccountName", "displayName", "mail"]
tls = false

[email]
smtpHost = "smtp.qq.com"
port = 465
username = "xx@qq.com"
password = "xx"
from = "xx@xx.com"
tls = false
anonymous = false
skipVerify = false